### ISSUE TITLE
Chart Area not filled correctly.

### ISSUE THREAD

**Issue by Neilfau** [ivanschuetz/SwiftCharts#391]
Im having an issue when using ChartPointsAreaLayer, for some reason the fill is not going to the end of the chart, it always stops 1 point before the end. Any ideas?

Update:
Seems to be linked to `addPaddingSegmentIfEdge: true`

![IMG_2C49347A1773-1](https://user-images.githubusercontent.com/1814989/58486640-1f16af00-815e-11e9-9843-46260b2de937.jpeg)

**Comment by woshahua** [comment]
@Neilfau I am absolutely fall into the same problem, can you tell me where to set this `addPaddingSegmentIfEdge: true` when you generate the arealayer, thank you
